spring.application.name=KudosOnchain

server.port=8000
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
app.slack.signing-secret=${SLACK_SIGNING_SECRET}
slack.client-id=${SLACK_CLIENT_ID}
slack.client.secret=${SLACK_CLIENT_SECRET}
slack.redirect-uri=${SLACK_REDIRECT_URI}
supabase.url=${SUPABASE_URL}
supabase.api.key=${SUPABASE_API_KEY}
supabase.bucket.name=${SUPABASE_BUCKET_NAME}
bot.token=${BOT_TOKEN}
